In [41]:
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt
import copy

%matplotlib inline

xls = pd.ExcelFile('General.xlsx')
df1 = pd.read_excel(xls, 'Table1a-PerCapitaAvail. (70-82)')
#df2 = pd.read_excel(xls, 'Sheet2')
print(type(df1))

print(df1.shape)
df1.head()

<class 'pandas.core.frame.DataFrame'>
(81, 14)

,"Table 1a--U.S. per capita availability of selected, commercially produced, fresh and processing vegetables and dry pulse crops.1",Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13
0,Crop,1970,1971,1972,1973,1974,1975,1976,1977,1978,1979,1980,1981,1982
1,NaN,—————————————————————————— Pounds per person ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,"Asparagus, all",1.33146,1.27763,1.26558,1.29273,1.09977,1.20263,1.22411,0.993376,0.845955,0.739564,0.785468,0.795705,0.720789
3,"Asparagus, fresh",0.441932,0.378627,0.403152,0.400342,0.388747,0.411755,0.431216,0.336019,0.288151,0.250605,0.293959,0.310428,0.377436
4,"Asparagus, canning",0.5949,0.629031,0.612521,0.644938,0.526749,0.58396,0.533087,0.45136,0.379119,0.321694,0.364339,0.37756,0.284871

In [42]:
df1_tran = df1.T

In [43]:
df1_tran.head()

,0,1,2,3,4,5,6,7,8,9,...,71,72,73,74,75,76,77,78,79,80
"Table 1a--U.S. per capita availability of selected, commercially produced, fresh and processing vegetables and dry pulse crops.1",Crop,NaN,"Asparagus, all","Asparagus, fresh","Asparagus, canning","Asparagus, freezing","Snap /Green beans, all","Snap /Green beans,fresh","Snap /Green beans, canning","Snap /Green beans, freezing",...,"2/ Beginning in 2012, data coverage for melons...",3/ In-shell basis.,4/ Includes domestically produced hothouse (gr...,"5/ Includes artichokes, brussels sprouts, eggp...","6/ Includes beets, green limas (1992-2014), sp...","7/ Includes green limas, spinach, and miscella...","8/ Fresh, canning, and freezing data do not su...",9/ Production from new areas in the upper Midw...,10/ Includes garbanzo beans (chickpeas).,"Source: USDA, Economic Research Service."
Unnamed: 1,1970,—————————————————————————— Pounds per person ...,1.33146,0.441932,0.5949,0.294629,7.6066,1.54839,4.66554,1.39267,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Unnamed: 2,1971,NaN,1.27763,0.378627,0.629031,0.269971,7.46437,1.51256,4.56198,1.38983,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Unnamed: 3,1972,NaN,1.26558,0.403152,0.612521,0.249909,7.4942,1.52742,4.61584,1.35094,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Unnamed: 4,1973,NaN,1.29273,0.400342,0.644938,0.247446,8.01341,1.42797,4.90334,1.6821,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [44]:
df1_tran.columns

RangeIndex(start=0, stop=81, step=1)

In [46]:
df1_tran.set_index(df1_tran[0], inplace = True)

In [49]:
df1_tran.columns = df1_tran.iloc[0]
df1_tran.head()

Crop,NaN,"Asparagus, all","Asparagus, fresh","Asparagus, canning","Asparagus, freezing","Snap /Green beans, all","Snap /Green beans,fresh","Snap /Green beans, canning","Snap /Green beans, freezing","Broccoli, all",...,"2/ Beginning in 2012, data coverage for melons is included in the Fruit and Tree Nuts Yearbook.",3/ In-shell basis.,4/ Includes domestically produced hothouse (greenhouse) tomatoes after 1996. All years include imported hothouse tomatoes.,"5/ Includes artichokes, brussels sprouts, eggplant, endive/escarole, garlic, radishes, green limas, squash, & spinach. After 2000 includes okra, pumpkins, kale, collards, turnip greens, and mustard greens.","6/ Includes beets, green limas (1992-2014), spinach, and miscellaneous imports (1990-2014).","7/ Includes green limas, spinach, and miscellaneous freezing vegetables.","8/ Fresh, canning, and freezing data do not sum to the total because onions for dehydrating are included in the total.",9/ Production from new areas in the upper Midwest added in 1998. A portion of this is used for animal feed.,10/ Includes garbanzo beans (chickpeas).,"Source: USDA, Economic Research Service."
0,,,,,,,,,,,,,,,,,,,,,
Crop,NaN,"Asparagus, all","Asparagus, fresh","Asparagus, canning","Asparagus, freezing","Snap /Green beans, all","Snap /Green beans,fresh","Snap /Green beans, canning","Snap /Green beans, freezing","Broccoli, all",...,"2/ Beginning in 2012, data coverage for melons...",3/ In-shell basis.,4/ Includes domestically produced hothouse (gr...,"5/ Includes artichokes, brussels sprouts, eggp...","6/ Includes beets, green limas (1992-2014), sp...","7/ Includes green limas, spinach, and miscella...","8/ Fresh, canning, and freezing data do not su...",9/ Production from new areas in the upper Midw...,10/ Includes garbanzo beans (chickpeas).,"Source: USDA, Economic Research Service."
1970,—————————————————————————— Pounds per person ...,1.33146,0.441932,0.5949,0.294629,7.6066,1.54839,4.66554,1.39267,1.49756,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1971,NaN,1.27763,0.378627,0.629031,0.269971,7.46437,1.51256,4.56198,1.38983,1.62089,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1972,NaN,1.26558,0.403152,0.612521,0.249909,7.4942,1.52742,4.61584,1.35094,1.62974,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1973,NaN,1.29273,0.400342,0.644938,0.247446,8.01341,1.42797,4.90334,1.6821,1.76982,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [54]:
df1_tran.columns

Index(['Asparagus, all ', 'Asparagus, fresh', 'Asparagus, canning',
       'Asparagus, freezing ', 'Snap /Green beans, all',
       'Snap /Green beans,fresh ', 'Snap /Green beans, canning',
       'Snap /Green beans, freezing  ', 'Broccoli, all ', 'Broccoli, fresh ',
       'Broccoli, freezing ', 'Cabbage, all ', 'Cabbage, fresh ',
       'Cabbage, canning ', 'Carrots, all ', 'Carrots, fresh ',
       'Carrots, canning ', 'Carrots, freezing ', 'Cauliflower, all ',
       'Cauliflower, fresh ', 'Cauliflower, freezing ', 'Celery',
       'Sweet corn, all 1', 'Sweet corn, fresh ', 'Sweet corn, canning ',
       'Sweet corn, freezing ', 'Cucumbers, all ', 'Cucumbers, fresh ',
       'Cucumbers, pickling ', 'Melons2', 'Watermelon', 'Cantaloupe',
       'Honeydew', 'Melons, other ', 'Lettuce, all ', 'Lettuce, head ',
       'Lettuce, leaf /romaine  ', 'Onions, all ', 'Onions, fresh ',
       'Onions, dehydrating ', 'Green peas, all 3', 'Green peas, canning ',
       'Green peas, freezing ', 'Peppers, all ', 'Peppers, bell ',
       'Peppers, chile ', 'Tomatoes, all ', 'Tomatoes, fresh 4',
       'Tomatoes, canning ', 'Other, fresh5', 'Other, canning6',
       'Other, freezing7', 'Subtotal w/o melons8', 'Fresh subtotal w/o melons',
       'Canning subtotal w/o melons', 'Freezing subtotal w/o melons',
       'Subtotal w/ melons8', 'Fresh subtotal w/ melons', 'Potatoes, all ',
       'Potatoes, fresh ', 'Potatoes, processing ', 'Sweet potatoes',
       'Mushrooms', 'Dry peas and lentils9', 'Dry beans10', 'Total w/o melons',
       'Total w/ melons ',
       '-- = Not available. Latest year of data is preliminary. Totals may not sum due to rounding. ',
       '1/ On-cob basis.',
       '2/ Beginning in 2012, data coverage for melons is included in the Fruit and Tree Nuts Yearbook.  ',
       '3/ In-shell basis.',
       '4/ Includes domestically produced hothouse (greenhouse) tomatoes after 1996. All years include imported hothouse tomatoes.',
       '5/ Includes artichokes, brussels sprouts, eggplant, endive/escarole, garlic, radishes, green limas, squash, & spinach.  After 2000 includes okra, pumpkins, kale, collards, turnip greens, and mustard greens.',
       '6/ Includes beets, green limas (1992-2014), spinach, and miscellaneous imports (1990-2014).',
       '7/ Includes green limas, spinach, and miscellaneous freezing vegetables.',
       '8/ Fresh, canning, and freezing data do not sum to the total because onions for dehydrating are included in the total.',
       '9/ Production from new areas in the upper Midwest added in 1998.  A portion of this is used for animal feed. ',
       '10/ Includes garbanzo beans (chickpeas).',
       'Source: USDA, Economic Research Service. '],
      dtype='object', name='Crop')

In [52]:
df1_tran.drop(columns = np.nan, inplace = True)

df1_tran.head()

KeyError: '[nan] not found in axis'